#!/usr/bin/env bash

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a backup of the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Configure the Nginx server block to handle the redirection
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
        listen [::]:80 default_server;

	    server_name _;

	        location /redirect_me {
		        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
			    }

		        # Additional server block configuration can be added here

		}
	EOL'

	# Restart Nginx to apply the changes
sudo service nginx restart
