#!/usr/bin/env bash 
#comment 

for ((i=1; i<=100; i++))
do 
	if ((i % 3 == 0)) && ((i % 5 == 0)); then
		echo "FizzBuzz"
	#Check if the number is divisible by 3 (Fizz)
	elif ((i % 3 == 0)); then
		echo "Fizz"
	# Check if the number is divisible by 5 (Buzz)
	elif ((i % 5 == 0)); then
		echo "Buzz"
	   # If none of the above conditions are met, simply print the number	
	else
	        echo "$i"
	fi
done 

