#!/usr/bin/env bash
#this script is doing great

i=1
while [ $i -le 20 ]
do	
	echo "$i" 
	i=$(( i + 1))
	if [ $i -eq 5 ]; then
		echo "bad luck from China"
	elif [ $i -eq 10 ]; then
		echo "bad luck from Japan"
	elif [ $i -eq  18 ]; then
		echo "bad luck from Italy"
	fi
done
