#!/usr/bin/env bash
#this will be a gooo exercice for all of us 

hours=0
minutes=1
 
while [ $hours -le 12 ]; do 
	echo "hour: $hours "
	while [ $minutes -le 59 ] ; do 
		echo "$minutes" 
		minutes=$(( minutes + 1 ))
	done
	minutes=1	
	hours=$(( hours + 1 ))
done
