#!/usr/bin/env bash
#terate through files in the current directory
file=$(ls)
for elem in $file; do
        # Use parameter expansion to extract the part after the first dash
        name="${elem#*-}"
        echo "$name"
done

